name: buildtest

on:
  workflow_dispatch:

jobs:
  buildtest:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: cmd test
        run: |
          dir
          tasklist
          git
          aws
          
      # - name: build test
      #   run: docker build -t win-unity-ruby:teste .
