name: buildtest

on:
  workflow_dispatch:

jobs:
  buildtest:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: cmd test
        run: |
          echo dir
          dir
          echo tasklist
          tasklist
          echo git --help
          git --help
          echo choco
          choco
          echo aws help
          aws help
          
      # - name: build test
      #   run: docker build -t win-unity-ruby:teste .
