name: buildtest

on:
  workflow_dispatch:

jobs:
  buildtest:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: cmd test
        run: |
          echo dir
          dir
          echo tasklist
          tasklist
          echo git --version
          git --version
          echo choco --version
          choco --version
          echo aws --version
          aws --version
          
      # - name: bat test
      #   shell: cmd
      #   run: test.bat

      # - name: env
      #   run: set

      - name: shell-bash
        shell: bash
        run: env | sort
        
      - name: bash
        run: |
          bash --version
      # - name: build test
      #   run: docker build -t win-unity-ruby:teste .

      - name: install 7zip
        shell: powershell
        run: |
          Invoke-WebRequest https://www.7-zip.org/a/7z2401-x64.exe -OutFile C:\Temp\7zip_installer.exe
          Start-Process -Wait -FilePath C:\Temp\7zip_installer.exe -ArgumentList "/S"
          del C:\Temp\7zip_installer.exe
      - name: run 7zip with path
        shell: cmd
        run: |
          "C:\Program Files\7-Zip\7z.exe" -version
      - name: run 7zip
        shell: cmd
        run: 7z.exe -version
      # - name: 7zip
      #   shell: powershell
      #   run: |
      #     Install-Module -Name 7Zip4PowerShell -Verbose -Force
      #     Get-Command -Module 7Zip4PowerShell
