name: buildtest

on:
  workflow_dispatch:

jobs:
  buildtest:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: cmd test
        run: |
          echo dir
          dir
          echo tasklist
          tasklist
          echo git --version
          git --version
          echo choco --version
          choco --version
          echo aws --version
          aws --version
          
      # - name: bat test
      #   shell: cmd
      #   run: test.bat

      # - name: env
      #   run: set

      - name: shell-bash
        shell: bash
        run: env | sort
        
      - name: bash
        run: |
          bash --version
      # - name: build test
      #   run: docker build -t win-unity-ruby:teste .

      - name: 7zip
        shell: powershell
        run: |
          Install-Module -Name 7Zip4PowerShell -Verbose -Force
          Get-Command -Module 7Zip4PowerShell
